site_name: Passio Go API Documentation
docs_dir: docs
repo_url: https://github.com/athuler/PassioGo
theme: readthedocs
copyright: © Andrei Thüler
site_author: Andrei Thüler

nav:
  - Home: index.md
#  - Examples: examples.md
  - API Reference: api.md
  - Changelog: changelog.md
  
#plugins:
#  - search
markdown_extensions:
  - markdown_include.include:
      base_path: .

watch:
    - .\README.md